import uuid

class data_used():
    field_empty = ""
    firstname = "Jessica"
    lastname = "Parker"
    email_used = "mahid34381@finghy.com"
    password = "PPuD9XmVT!qsg"
    unique = str(uuid.uuid4().hex)
    new_email = "jessicaparkerishere" + unique + "@example.com"
    confpass_mismatch = "confpass123"
    email_wrong = "notfoundexample@example."
    password_less = "test"
    firstname_empty = "First name is required."
    lastname_empty = "Last name is required."
    email_empty = "Email is required."
    password_empty = "Password is required."
    confpass_empty = "Password is required."
    success_register = "Your registration completed"
    email_exists = "The specified email already exists"
    confpass_mismatch_message = "The password and confirmation password do not match."
    email_wrong_message = "Wrong email"
    password_less_message = "The password should have at least 6 characters."
    login_wrong_message = "Login was unsuccessful. Please correct the errors and try again."
    no_account = "No customer account found"
    wrong_cred = "The credentials provided are incorrect"
    email_inv_message = "Please enter a valid email address."
    laptop_name = "14.1-inch Laptop"
    add_to_cart = "Add to cart"
    quantity = "3"