class locator_used():
    register_menu = ".ico-register"
    firstname = "input#FirstName"
    lastname = "input#LastName"
    email = "input#Email"
    password = "input#Password"
    conf_pass = "input#ConfirmPassword"
    firstname_empty = "[data-valmsg-for] [for='FirstName']"
    lastname_empty = "[data-valmsg-for] [for='LastName']"
    email_empty = "[data-valmsg-for] [for='Email']"
    password_empty = "[data-valmsg-for] [for='Password']"
    confpass_empty = "[data-valmsg-for] [for='ConfirmPassword']"
    register_button = "input#register-button"
    continue_button = ".button-1.register-continue-button"
    success_register = ".result"
    radio_male = "input#gender-male"
    radio_female = "input#gender-female"
    email_exists = ".validation-summary-errors li"
    logout_menu = ".ico-logout"
    confpass_mismatch = "[data-valmsg-for] [for]"
    login_menu = ".ico-login"
    login_wrong = ".validation-summary-errors span"
    no_account = ".validation-summary-errors li"
    login_button = "[action='\/login'] [type='submit']"
    email_menu = ".header-links .account"
    laptop_name = "[data-productid] .details [href='\/141-inch-laptop']"
    landing_to_cart = "[data-productid='31'] [class='button-2 product-box-add-to-cart-button']"
    laptop_detail = "h1[itemprop='name']"
    add_to_cart = ".add-to-cart-button.button-1"
    quantity = "input[name='addtocart_31.EnteredQuantity']"
    cart_inside = "#topcartlink .cart-label"